// Code generated by Icestudio 0.10-rc1
// Mon, 14 Nov 2022 05:22:05 GMT

// Testbench template

`default_nettype none
`define DUMPSTR(x) `"x.vcd`"
`timescale 10 ns / 1 ns


module main_tb
;
 
 // Simulation time: 100ns (10 * 10ns)
 parameter DURATION = 10;
 
 // Input/Output
 reg clk;
 reg ascii_in;
 wire ASCII_OUT;
 
 // Module instance
 main MAIN (
  .v6198d7(clk),
  .v301e5f(ascii_in),
  .ve27779(ASCII_OUT)
 );
 
 // Clock signal
 always #0.5 clk = ~clk;
 
 initial begin
  // File were to store the simulation results
  $dumpfile(`DUMPSTR(`VCD_OUTPUT));
  $dumpvars(0, main_tb);
 
  // TODO: initialize the registers here
  // e.g. value = 1;
  // e.g. #2 value = 0;
  clk = 0;
  ascii_in = 0;
 
  #(DURATION) $display("End of simulation");
  $finish;
 end
 
endmodule
